/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './compo-place.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './compo-place.component';
const styles_CompoPlaceComponent:any[] = [i0.styles];
export const RenderType_CompoPlaceComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_CompoPlaceComponent,data:{}});
export function View_CompoPlaceComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),3,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
      1,'a',[['href','https://placeholder.com']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵeld(0,(null as any),(null as any),
      0,'img',[['src','http://via.placeholder.com/350x150']],(null as any),(null as any),
      (null as any),(null as any),(null as any)))],(null as any),(null as any));
}
export function View_CompoPlaceComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-compo-place',
      ([] as any[]),(null as any),(null as any),(null as any),View_CompoPlaceComponent_0,
      RenderType_CompoPlaceComponent)),i1.ɵdid(114688,(null as any),0,i2.CompoPlaceComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const CompoPlaceComponentNgFactory:i1.ComponentFactory<i2.CompoPlaceComponent> = i1.ɵccf('app-compo-place',
    i2.CompoPlaceComponent,View_CompoPlaceComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2Nhcmxvc3JvamFzby9EZXNrdG9wL2NvbXBvLXBsYWNlL2NvbXBvLXBsYWNlLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9jYXJsb3Nyb2phc28vRGVza3RvcC9jb21wby1wbGFjZS9jb21wby1wbGFjZS5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9jYXJsb3Nyb2phc28vRGVza3RvcC9jb21wby1wbGFjZS9jb21wby1wbGFjZS5jb21wb25lbnQudHMuQ29tcG9QbGFjZUNvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvY2FybG9zcm9qYXNvL0Rlc2t0b3AvY29tcG8tcGxhY2UvY29tcG8tcGxhY2UuY29tcG9uZW50LnRzLkNvbXBvUGxhY2VDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cbiAgPGEgaHJlZj1cImh0dHBzOi8vcGxhY2Vob2xkZXIuY29tXCI+PGltZyBzcmM9XCJodHRwOi8vdmlhLnBsYWNlaG9sZGVyLmNvbS8zNTB4MTUwXCI+PC9hPjwvcD4iLCI8YXBwLWNvbXBvLXBsYWNlPjwvYXBwLWNvbXBvLXBsYWNlPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFHO2FBQUEsMEJBQ0Q7TUFBQTtNQUFBLDhCQUFrQztNQUFBO01BQUE7OztvQkNEcEM7TUFBQTtvQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
